### ISSUE TITLE
Gui crashes on startup- pos undefined

### ISSUE THREAD

**Issue by Bob-Thomas** [aldewereld/practicum-atp#1]
Pos word alleen gezet in in de mousedown maar weer gebruikt in de volgende else
`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    simulator.run()
  File "C:\Users\endargon\school\atp\practicum-atp\simulator\Simulator.py", line 73, in run
    self._Simulator__gui.run()
  File "C:\Users\endargon\school\atp\practicum-atp\simulator\Gui.py", line 192, in run
    if 10 < pos[1] <= 40 and pos[0] > 560:
UnboundLocalError: local variable 'pos' referenced before assignment
`

**Comment by Bob-Thomas** [comment]
hmm uncompyle2 did something with the IF structure.
I am guessing it should be fine with the original source
